//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecommerce.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer_Payment_Methods
    {
        public int customer_payment_id { get; set; }
        public int customer_id { get; set; }
        public byte payment_method_code { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Ref_Payment_Methods Ref_Payment_Methods { get; set; }
    }
}
