//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecommerce.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoices
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Invoices()
        {
            this.Payments = new HashSet<Payments>();
        }
    
        public int invoice_number { get; set; }
        public int order_id { get; set; }
        public byte invoice_status_code { get; set; }
        public System.DateTime invoice_date { get; set; }
        public string invoice_details { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Ref_Invoice_Status_Codes Ref_Invoice_Status_Codes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payments> Payments { get; set; }
    }
}
